const ENDPOINTS = {
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    logout: "/auth/logout",
    me: "/auth/me",
    switchTenant: "/auth/switch-tenant",
  },
  projects: {
    list: "/projects",
    create: "/projects",
    one: "/projects/:projectId",
    update: "/projects/:projectId",
    delete: "/projects/:projectId",
  },
  tasks: {
    list: "/projects/:projectId/tasks",
    create: "/projects/:projectId/tasks",
    one: "/projects/:projectId/tasks/:taskId",
    update: "/projects/:projectId/tasks/:taskId",
    delete: "/projects/:projectId/tasks/:taskId",
  },
  myTasks: {
    list: "/my-tasks",
    summary: "/my-tasks/summary",
  },
  timeEntries: {
    get: "/tasks/:taskId/time-entries",
    create: "/tasks/:taskId/time-entries",
    active: "/time-entries/active",
  },
  tenants: {
    list: "/tenants",
    one: "/tenants/:tenantId",
    slug: "/tenants?slug=:tenantSlug",
    create: "/tenants",
    update: "/tenants/:tenantId",
    delete: "/tenants/:tenantId",
  },
  users: {
    list: "/users",
    one: "/users/:userId",
    updateRole: "/users/:userId/role",
    invite: "/users/invite",
    remove: "/users/:userId",
    search: "/users/search",
  },
  roles: {
    list: "/roles",
  },
  invitations: {
    list: "/invitations",
    create: "/invitations",
    resend: "/invitations/:invitationId/resend",
    cancel: "/invitations/:invitationId",
    validate: "/invitations/validate/:token",
    myInvitations: "/invitations/my-invitations",
    accept: "/invitations/:invitationId/accept",
    reject: "/invitations/:invitationId/reject",
  },
  notifications: {
    list: "/notifications",
    unreadCount: "/notifications/unread-count",
    one: "/notifications/:notificationId",
    markAsRead: "/notifications/:notificationId/read",
    markAllAsRead: "/notifications/mark-all-read",
    delete: "/notifications/:notificationId",
  },
  notificationPreferences: {
    list: "/notification-preferences",
    defaults: "/notification-preferences/defaults",
    update: "/notification-preferences/:type",
    muteAll: "/notification-preferences/mute/all",
    unmuteAll: "/notification-preferences/unmute/all",
  },
  customers: {
    list: "/customers",
    create: "/customers",
    one: "/customers/:customerId",
    update: "/customers/:customerId",
    delete: "/customers/:customerId",
    search: "/customers/search",
  },
  invoices: {
    list: "/invoices",
    create: "/invoices",
    one: "/invoices/:invoiceId",
    update: "/invoices/:invoiceId",
    delete: "/invoices/:invoiceId",
    generate: "/invoices/generate",
    updateStatus: "/invoices/:invoiceId/status",
    send: "/invoices/:invoiceId/send",
    generatePdf: "/invoices/:invoiceId/pdf",
  },
};

export default ENDPOINTS;
